title: DreamChess
theme: null
gallery_path: /assets/images/screenshots/
gallery_thumb_prefix: tn_
permalink: /news/:categories/:year/:month/:day/:title.html
paginate_path: /news/page:num/
paginate: 5
defaults:
  -
    values:
      layout: default
